$(function(){$('.index-news-block__hide').on('click',function(){$('.index-news-block__message').toggle();$(this).toggleClass('active');});$('.pay__history').on('click','.details__tr_js',function(){var $arrow=$(this).find('.details__arrow');var link=$arrow.attr('data-link');$arrow.toggleClass('details__arrow-on');$('#details_'+link).toggle();$('#trade_type_arrow_'+link).toggleClass('details-on');});$('.pay__buy_top ').on('keyup paste input change','.user_item_price_js',function(){set_sell_item_info();$('.pay__buy_top .bet-content__betcoin_money').text(toFixed($(this).val()-$('span.commission_js').html(),2)+'$').data('betcoin',$(this).val());checkNoCoins();})
$('.pay__tabs').on('click','.game_item',function(e){if(e.target.tagName!='INPUT'){return;}
if($(this).parent().hasClass('items_my')){if($(this).parents().hasClass('pay__sell__tabs_content_js')){$('.pay__sell__tabs_content_js .items__tabs_middle_js .game_item').each(function(i,element){$(element).find('input.item_checkbox_js').click();});}
$(this).find('input.item_checkbox_js').prop('checked',true);$('.items__tabs_middle_js:visible').prepend($(this));}else if($(this).parent().hasClass('items__tabs_middle_js')){$(this).find('input.item_checkbox_js').prop('checked',false);$('.items__tabs_bottonm-weapon .items_my:visible').prepend($(this));}
if($('.items__tabs_middle_js:visible .game_item').length==0){$('.items__tabs_middle-betcoin:visible .items__tabs_middle-no_item-bottom').show();}else{$('.items__tabs_middle-betcoin:visible .items__tabs_middle-no_item-bottom').hide();}
set_sell_item_info(true);calcItems();fix_horisontal_margins('.margin_fix_js','.game_item',5);;});function set_sell_item_info(new_item=false){var $item_value_div=$('.pay__buy_top-left div.item_value:visible');if(new_item&&$item_value_div.data('price')){$('.pay__sell .user_item_price_js').val($item_value_div.data('price'));}
if(new_item&&$('.pay__sell .user_item_price_js').attr('min')&&$('.pay__sell .user_item_price_js').attr('min')>$('.pay__sell .user_item_price_js').val()){$('.pay__sell .user_item_price_js').val($('.pay__sell .user_item_price_js').attr('min'));}
var $item_price=$('.pay__sell .user_item_price_js').val();if($item_value_div){var $commision=$item_value_div.data('selling_items_cof')*$item_price;if($commision<0.01){$commision=0.01;}
var $avg_price=$item_value_div.data('selling_items_avg')?$item_value_div.data('selling_items_avg'):0;var $min_price=$item_value_div.data('selling_items_min_price')?$item_value_div.data('selling_items_min_price'):0;var $max_price=$item_value_div.data('selling_items_max_price')?$item_value_div.data('selling_items_max_price'):0;}else{var $commision=0;var $avg_price=0;var $min_price=0;var $max_price=0;}
$('.commission_js').text(toFixed($commision,2));$('.avg_price_js').text($avg_price);$('.min_price_js').text($min_price);$('.max_price_js').text($max_price);}
$('.pay__tab_title').on('click',function(){if($(this).hasClass('checked')){return;}
$('.pay__tab_title').removeClass('pay__tab_title-active');$(this).addClass('pay__tab_title-active');$('.pay__tab_content').hide().removeClass('checked');$('.js_user_trades_info_sell').hide();if($(this).hasClass('pay__buy__tabs_title_js')){$('.pay__buy__tabs_content_js').show().addClass('checked');}else if($(this).hasClass('pay__sell__tabs_title_js')){$('.pay__sell__tabs_content_js').show().addClass('checked');$('.js_user_trades_info_sell').show();}else if($(this).hasClass('pay__history__tabs_title_js')){$('.pay__history__tabs_content_js').show().addClass('checked');}
calcItems();})
$('.pay__sell__tabs_content_js').on('click','.button-load-ajax',function(){var contentWrapper=$(this).parents('.items_my');var url=contentWrapper.data('url');contentWrapper.empty();contentWrapper.append(loading_html);$.ajax({url:url,success:function(result){contentWrapper.html(result);calcItems();sort_by_price_sell(-1);fix_horisontal_margins('.margin_fix_js','.game_item',5);;}});});$('.items__tabs_bottom-tabs').on('click','div',function(){if($(this).hasClass('checked')){return;}
var show_container=$(this).data('show_container');$('.pay__sell .items__tabs_bottom-tabs div').removeClass('checked');$(this).addClass('checked');$('.pay__sell .items-tab').removeClass('checked').hide();$(show_container).addClass('checked').show();calcItems();});$('.items__tabs_bottom').on('click','.items__tabs_bottom-top-sort',function(){sort_by_price_sell();});$('.items__tabs_bottom').on('keyup','.search_site_items_input_js',function(){if($(this).is("#search_site_items_input_buy")){return;}
var search_name=$(this).val().toLowerCase();var $items_my=$('.items__tabs_bottonm-weapon .items_my:visible');$items_my.children('.game_item').each(function(){if($(this).text().toLowerCase().includes(search_name)){$(this).show();}else{$(this).hide();}});calcItems();})
function sort_by_price_sell(order){var $items_my=$('.items__tabs_bottonm-weapon .items_my:visible');var $items_my_item=$items_my.children('.game_item');var $order=$(this).data('order-deposit');if(typeof $order==='undefined'){$order=-1;}
if(typeof order!='undefined'){$order=order;}
$items_my_item.sort(function(a,b){var an=$(a).find('.item_value').data('price'),bn=$(b).find('.item_value').data('price');if(!$(a).hasClass('nice_item')&&$(b).hasClass('nice_item')){return 1;}
if(an>bn){return 1*$order;}
if(an<bn){return-1*$order;}
return 0;});$(this).data('order-deposit',-1*$order);set_sort_arrows($order);$items_my_item.detach().appendTo($items_my);}
$('.items__tabs_bottom').on('change','.rarity_filter',function(){var $rarity=$(this).val();var $items_my=$('.items__tabs_bottonm-weapon .items_my:visible');$items_my.children('.game_item').each(function(){if($(this).find('.item_type').data('rarity')==$rarity||$rarity=='Rarity All'){$(this).show();}else{$(this).hide();}});calcItems();});function calcItems(){var sumPrice=0;$('.items__tabs_middle_js:visible .game_item:visible').each(function(){sumPrice+=parseFloat($(this).find('.item_value').data('price'));});sumPrice=toFixed(sumPrice,2);if(sumPrice>0&&$('.pay__buy_top .user_item_price_js:visible').val()>0){sumPrice=toFixed($('.pay__buy_top .user_item_price_js:visible').val(),2);}
$('.bet-content__betcoin_money:visible').text(toFixed(sumPrice-$('span.commission_js').html(),2)+'$').data('betcoin',sumPrice);$('.user_item_price_js:visible').val(sumPrice);var sumBotPrice=0;$('.items__tabs_bottonm-weapon:visible .game_item:visible').each(function(){sumBotPrice+=parseFloat($(this).find('.item_value').data('price'));});sumBotPrice=toFixed(sumBotPrice,2);$('.items__tabs_bottom .user_items_price:visible').text(sumBotPrice);checkNoCoins();}
function checkNoCoins(){var $betcoin_div=$('.items__tabs_middle-betcoin-bottom:visible');if($betcoin_div.find('.bet-content__betcoin_money').data('betcoin')>0.001){$betcoin_div.removeClass('no-coins');}else{$betcoin_div.addClass('no-coins');}}
$('body').on('click','.load_button_more_items_to_buy',function(){$(this).parents('.btn_div').remove();LoadBuyItems();});var buy_sort_by_price=0;var buy_sort_by_discount=1;var buy_sort_by_rarity="Rarity All";var buy_sort_by_game="Game All";var buy_sort_by_name="";var buy_sort_item_start_index=0;var buy_num_of_items_per_load=200;try{buy_num_of_items_per_load=Math.floor(parseInt($('.items__tabs_bottonm-weapon:visible').width())/(105+5+5))*20;}
catch(e){console.error(e);}
if(!buy_num_of_items_per_load){buy_num_of_items_per_load=200;}
var is_loading_new_items_buy=false;LoadBuyItems();function LoadBuyItems(){if(is_loading_new_items_buy){return;}
if($("#search_site_items_input_buy").val().length>minlengthSearch){buy_sort_by_name=$("#search_site_items_input_buy").val();}else{buy_sort_by_name='';}
var items_in_receiving_tab_inputs=$('.pay__buy_top .items__tabs_middle_js .game_item input.item_checkbox_js');var items_in_receiving_tab_ids=[];for(var index=0;index<items_in_receiving_tab_inputs.length;index++){const element=items_in_receiving_tab_inputs[index];items_in_receiving_tab_ids.push($(element).val());}
if(buy_sort_item_start_index===0){$("#all_items_to_buy").empty();}
is_loading_new_items_buy=true;$("#all_items_to_buy").append(loading_html);var post_data={sort_by_price:buy_sort_by_price,sort_by_discount:buy_sort_by_discount,sort_by_rarity:buy_sort_by_rarity,sort_by_game:buy_sort_by_game,sort_by_name:buy_sort_by_name,sort_item_start_index:buy_sort_item_start_index,num_of_items_per_load:buy_num_of_items_per_load,items_ids_exclude:JSON.stringify(items_in_receiving_tab_ids)};var posting=$.post('https://'+window.location.host+'/engine/function/user_trades_loader.php?buy',post_data);posting.done(function(data){buy_sort_item_start_index+=buy_num_of_items_per_load;is_loading_new_items_buy=false;$("#all_items_to_buy").append(data);});posting.always(function(){$("#all_items_to_buy #loading").remove();$('#clear_load_button_all_items_to_ex_my_items_load').remove();is_loading_new_items_buy=false;calcItems();fix_horisontal_margins('.margin_fix_js','.game_item',5);;});};$('.pay__buy').on('change','.rarity_filter',function(){buy_sort_by_rarity=$(this).val();buy_sort_by_game='Game All';$('.pay__buy .selectbox_game').val(buy_sort_by_game);buy_sort_item_start_index=0;LoadBuyItems();});$('.pay__buy').on('change','.selectbox_game',function(){buy_sort_by_game=$(this).val();buy_sort_by_rarity='Rarity All';$('.pay__buy .rarity_filter').val(buy_sort_by_rarity);buy_sort_item_start_index=0;LoadBuyItems();});var minlengthSearch=3;$('.pay__buy_bottom').on('keyup','#search_site_items_input_buy',function(){var value=$(this).val();if(buy_sort_by_name!=value&&(value.length>=minlengthSearch||value.length==0)){buy_sort_by_name=value;buy_sort_item_start_index=0;LoadBuyItems();}});$('.pay__buy').on('click','.items__tabs_bottom-top-sort_price',function(){buy_sort_item_start_index=0;sort_by_price_buy();});$('.pay__buy').on('click','.items__tabs_bottom-top-sort_discount',function(){buy_sort_item_start_index=0;sort_by_discount_buy();});function sort_by_price_buy(order){var $order=$(this).data('order-withdraw');if(typeof $order==='undefined'){$order=-1;}
if(typeof order!='undefined'){$order=order;}
$(this).data('order-withdraw',-1*$order);buy_sort_by_price=-1*$order;buy_sort_by_discount=0;set_sort_arrows($order);set_sort_arrows_discount(0);LoadBuyItems();}
function sort_by_discount_buy(order){var $order=$(this).data('order-withdraw');if(typeof $order==='undefined'){$order=-1;}
if(typeof order!='undefined'){$order=order;}
$(this).data('order-withdraw',-1*$order);buy_sort_by_price=0;buy_sort_by_discount=-1*$order;set_sort_arrows(0);set_sort_arrows_discount($order)
LoadBuyItems();}
function set_sort_arrows(order){if(order==1){$('.sort_items_by_price_js_up:visible').removeClass('active');$('.sort_items_by_price_js_down:visible').addClass('active');}else if(order==-1){$('.sort_items_by_price_js_up:visible').addClass('active');$('.sort_items_by_price_js_down:visible').removeClass('active');}else{$('.sort_items_by_price_js_up:visible').removeClass('active');$('.sort_items_by_price_js_down:visible').removeClass('active');}}
function set_sort_arrows_discount(order){if(order==1){$('.sort_items_by_discount_js_up:visible').removeClass('active');$('.sort_items_by_discount_js_down:visible').addClass('active');}else if(order==-1){$('.sort_items_by_discount_js_up:visible').addClass('active');$('.sort_items_by_discount_js_down:visible').removeClass('active');}else{$('.sort_items_by_discount_js_up:visible').removeClass('active');$('.sort_items_by_discount_js_down:visible').removeClass('active');}}
$(window).resize(function(){fix_horisontal_margins('.margin_fix_js','.game_item',5);;});$('.pay__history__tabs_content_js').on('click','.button-load-ajax',function(){load_more_history();});let history_page=0;load_more_history();function load_more_history(){var contentWrapper=$('#history_table_js');let loading_div=$('.pay__history .loading-div');let load_btn=$('.pay__history .button-load-ajax');var url=contentWrapper.data('url')+`?page=${history_page}`;load_btn.hide();loading_div.show();$.ajax({url:url,success:function(result){if(!result||result.trim()=="NONE"){loading_div.hide();load_btn.hide();return;}
loading_div.hide();load_btn.show();contentWrapper.append(result);$(window).trigger('resize');history_page++;}});}})